config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  root 'home#index'
  resources :r_packages, only: [:show]
  mount ResqueWeb::Engine => "/resque-web"
end

app/models/author.rb
# Details of an Author of any R Package Version
# An Author can have many Versions
# A RPackage can have many Authors through its Versions
#
class Author < ActiveRecord::Base
  has_many :version_committers
  has_many :versions, through: :version_committers
  has_many :r_packages, through: :versions

  validates_presence_of :email

  def identity
    "#{name}, (#{email})"
  end

end

app/models/r_package.rb
require 'package_refinement_job'
class RPackage < ActiveRecord::Base
  has_many :versions
  has_many :authors, through: :versions
  has_many :maintainers, through: :versions

  validates_presence_of :name

  def update_version version_data
    version = versions.find_by number: version_data[:number]
    if version
      version.update version_data
    else
      version = Version.create version_data.merge({r_package_id: self.id})
    end
    # Unhooking resque to not pay for heroku workers
    # Resque.enqueue(PackageRefinementJob, version.id)
    PackageRefinementJob.perform(version.id)
  end
end

app/models/version.rb
# The Version class mainatians R Package Versions. It also assocites with Authors and Maintainers
# A Version can have only one Author and many Maintainers.
#
class Version < ActiveRecord::Base
  belongs_to :r_package
  has_one :author_committer, -> { where "version_committers.role in ('author', 'all')" },
    class_name: "VersionCommitter"
  has_one :author, through: :author_committer
  has_many :maintainer_committers, -> { where "version_committers.role in ('maintainer', 'all')" },
    class_name: "VersionCommitter"
  has_many :maintainers, through: :maintainer_committers

  validates_presence_of :r_package_id, :number

  def package_name
    r_package.name
  end

  def set_author author_hash
    return unless author_hash[:email].present?
    v_author = Author.find_or_create_by email: author_hash[:email]
    v_author.update(author_hash)
    return if author == v_author
    if author_committer.present?
      author_committer.update(author_id: v_author.id) and return
    end
    maintainer_committer = maintainer_committers.find_by(author_id: v_author.id, role: "maintainer")
    if maintainer_committer
      maintainer_committer.update(role: "all")
    else
      VersionCommitter.create(version_id: id, author_id: v_author.id, role: "author")
    end
  end

  def add_maintainer maintainer_hash
    return unless maintainer_hash[:email].present?
    v_maintainer = Author.find_or_create_by email: maintainer_hash[:email]
    v_maintainer.update(maintainer_hash)
    return if maintainers.include?(v_maintainer)
    if author_committer and author_committer.author_id == v_maintainer.id
      author_committer.update(role: "all")
    else
      VersionCommitter.create(version_id: id, author_id: v_maintainer.id, role: "maintainer")
    end
  end

  def author_identity
    author.identity if author
  end

  def maintainers_details
    maintainers.map{|maintainer| maintainer.identity }.join(", ")
  end
end

app/models/version_committer.rb
class VersionCommitter < ActiveRecord::Base
  belongs_to :author, -> { where "version_committers.role in ('author', 'all')" }
  belongs_to :version
  belongs_to :maintainer, -> { where "version_committers.role in ('maintainer', 'all')" },
    class_name: "Author", foreign_key: :author_id

  @@valid_roles = [:author, :maintainer, :all]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @r_packages = RPackage.first(50)
  end
end

app/controllers/r_packages_controller.rb
class RPackagesController < ApplicationController
  def show
    @r_package = RPackage.find(params[:id])
    @versions = @r_package.versions
  end
end

app/helpers/application_helper.rb
require "r_package_fetcher"
module ApplicationHelper
  def download_path_for(r_package, version)
    RPackageFetcher.new.get_package_url_for r_package, version
  end
end

app/views/home/index.html.haml
.page-header
  %h1 The R Package Finder makes it very easy to look for R packages
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Title
      %th Description
      %th Created On
      %th License
  %tbody
    - @r_packages.each do |r_package|
      %tr
        %td= link_to r_package.name, r_package_path(r_package)
        %td= r_package.title
        %td= r_package.description
        %td= r_package.date_created
        %td= r_package.license

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "RPackager"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.png', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          =link_to "R Package Finder", root_path, :class => "brand"
    .container-fluid
      .row-fluid
        .span12
          = bootstrap_flash
          = yield
      %footer
        %p.pull-right &copy; R Package Finder 2014

app/views/r_packages/show.html.haml
.page-header
  %h3= @r_package.name
  %span= @r_package.title
%p= @r_package.description
%p
  %strong Created On :
  = @r_package.date_created
%p
  %strong License :
  = @r_package.license

.page-header
  %h4 Versions available
%table.table.table-striped
  %thead
    %tr
      %th Number
      %th Author
      %th Maintainers
      %th Released on
      %th Dependency
      %th Date/Publication
  %tbody
    - @versions.each do |version|
      %tr
        %td= version.number
        %td= version.author_identity
        %td= version.maintainers_details
        %td= version.released_on
        %td= version.dependency
        %td= version.publication_date
        %td= link_to "Download", download_path_for(@r_package.name, version.number), :class => 'btn'